name: 👷 Contribute to next priorities | Contribuer aux prochaines priorités
description: Help us with our work on our next priorities | Participez à nos travaux sur nos prochaines priorités.
title: 'contribution: '
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: |
        - Before we start developing these components or patterns, we want to ensure that the GC community has an opportunity to submit contributions that can accelerate and inform design and delivery.
        - The types of contributions we'll be looking for:
          - **examples of designs**: screenshots, prototypes, links to live services
          - **research findings**: tell or show us your discovery, your use case, or how your relevant prototype or service has been tested with people using the service
          - **code**: prototype code or production code; share your implementations of the relevant component or pattern in services
  - type: markdown
    attributes:
      value: "## Merci de participer à notre projet!"
  - type: markdown
    attributes:
      value: |
        - Avant que nous entamions le développement de ces composants ou configurations, nous souhaitons nous assurer que la communauté du GC a eu l’occasion de soumettre des contributions qui peuvent éclairer et accélérer la conception et le développement.
        - Voici les types de contributions que nous recherchons :
          - **Exemples de designs** : captures d’écran, prototypes, liens vers des services en ligne.
          - **Résultats de recherche** : recherches exploratoires, exemple de cas d’utilisation ou tests d’utilisabilité d’un prototype ou d’un service.
          - **Code** : code de prototype ou de production, ou implémentations du produit.

  - type: checkboxes
    attributes:
      label: Prerequisites | Prérequis
      description: |
        Complete all of the following.
        Assurez-vous de respecter les mesures suivantes.
      options:
        - label: I've read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md). | J’ai lu les [Lignes directrices sur les contributions](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md)
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md). | J’accepte de me conformer au [Code de conduite](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: dropdown
    id: contribution-type
    attributes:
      label: Which component or pattern is this contribution for? | Quel composant ou quelle configuration cette contribution vise-t-elle?
      options:
        - Data Table | Tableau de données
        - Tags | Étiquettes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your contribution. | Décrivez votre contribution
      description: Attach screenshots, or a detailed description of your contribution. | Ajoutez des captures d’écran ou des descriptions détaillées.
    validations:
      required: true
