/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Validator, ValidatorEntry } from "./validators";
export namespace Components {
    interface GcdsAlert {
        /**
          * Defines alert role.
         */
        "alertRole"?: 'danger' | 'info' | 'success' | 'warning';
        /**
          * Defines the max width of the alert content.
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Callback when the close button is clicked.
         */
        "dismissHandler": Function;
        /**
          * Defines the alert heading.
         */
        "heading": string;
        /**
          * Defines if the alert's close button is displayed or not.
         */
        "hideCloseBtn"?: boolean;
        /**
          * Defines if the alert's role icon is displayed or not.
         */
        "hideRoleIcon"?: boolean;
        /**
          * Defines if the alert's position is fixed.
         */
        "isFixed"?: boolean;
    }
    interface GcdsBreadcrumbs {
        /**
          * Defines if the default canada.ca link should be displayed or not.
         */
        "hideCanadaLink": boolean;
    }
    interface GcdsBreadcrumbsItem {
        /**
          * Specifies the href of the breadcrumb item.
         */
        "href": string | undefined;
    }
    interface GcdsButton {
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * The buttonId attribute specifies the id for a <button> element.
         */
        "buttonId": string;
        /**
          * Set the main style
         */
        "buttonRole": 'primary' | 'secondary' | 'danger' | 'skip-to-content';
        /**
          * Set the style variant
         */
        "buttonStyle": 'solid' | 'text-only';
        /**
          * Custom callback function on click event
         */
        "clickHandler": Function;
        /**
          * The disabled attribute for a <button> element.
         */
        "disabled": boolean;
        /**
          * The download attribute specifies that the target (the file specified in the href attribute) will be downloaded when a user clicks on the hyperlink
         */
        "download": string | undefined;
        /**
          * Focus element
         */
        "focusElement": () => Promise<void>;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * The href attribute specifies the URL of the page the link goes to
         */
        "href": string | undefined;
        /**
          * The name attribute specifies the name for a <button> element.
         */
        "name": string | undefined;
        /**
          * The rel attribute specifies the relationship between the current document and the linked document
         */
        "rel": string | undefined;
        /**
          * Set the button size
         */
        "size": 'regular' | 'small';
        /**
          * The target attribute specifies where to open the linked document
         */
        "target": string | undefined;
        /**
          * Set button types
         */
        "type": 'submit' | 'reset' | 'button' | 'link';
    }
    interface GcdsCheckbox {
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Id attribute for an input element.
         */
        "checkboxId": string;
        /**
          * Specifies if an input element is checked.
         */
        "checked": boolean;
        /**
          * Custom callback function on click event
         */
        "clickHandler": Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled": boolean;
        /**
          * Error message for an invalid input element.
         */
        "errorMessage": string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Hint displayed below the label.
         */
        "hint": string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Name attribute for an input element.
         */
        "name": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required": boolean;
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for an input element.
         */
        "value": string;
    }
    interface GcdsContainer {
        /**
          * Defines if container is centered or not
         */
        "centered"?: boolean;
        /**
          * Defines container size
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Set tag for container
         */
        "tag"?: string;
    }
    interface GcdsDateModified {
    }
    interface GcdsDetails {
        /**
          * The details title summarizes the panel content.
         */
        "detailsTitle": string;
        /**
          * Defines if the details panel is open by default or not.
         */
        "open"?: boolean;
    }
    interface GcdsErrorMessage {
        /**
          * Error message for an invalid form field.
         */
        "message": string;
        /**
          * Id attribute for the error message.
         */
        "messageId": string;
    }
    interface GcdsErrorSummary {
        /**
          * Object of list items for error list. Format: { link-href: link-label }
         */
        "errorLinks": string | object;
        /**
          * Set error summary heading
         */
        "heading"?: string;
        /**
          * Specifies if the error summary should listen for GcdsError event to generate error list.
         */
        "listen"?: boolean;
        /**
          * Set error summary message
         */
        "subHeading"?: string;
    }
    interface GcdsFieldset {
        /**
          * Flag to disable fieldset and its contents
         */
        "disabled": boolean;
        /**
          * Error message for invalid form elements in group.
         */
        "errorMessage": string;
        /**
          * The unique identifier for the component
         */
        "fieldsetId": string;
        /**
          * Hint displayed below the legend.
         */
        "hint": string;
        /**
          * The title for the contents of the fieldset
         */
        "legend": string;
        /**
          * Flag the contents are required
         */
        "required": boolean;
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
    }
    interface GcdsFileUploader {
        /**
          * Defines the file types the file uploader accepts.
         */
        "accept": string;
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler": Function;
        /**
          * Specifies if a file uploader element is disabled or not.
         */
        "disabled": boolean;
        /**
          * Error message for an invalid file uploader element.
         */
        "errorMessage": string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Hint displayed below the label.
         */
        "hint": string;
        /**
          * Form field label.
         */
        "label": string;
        /**
          * Boolean that specifies if the user is allowed to select more than one file.
         */
        "multiple": boolean;
        /**
          * Specifies if a form field is required or not.
         */
        "required": boolean;
        /**
          * Id attribute for a file uploader element.
         */
        "uploaderId": string;
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for a file uploader element.
         */
        "value": string[];
    }
    interface GcdsFooter {
        /**
          * Heading for contextual slot and nav landmark
         */
        "contextualHeading": string;
        /**
          * Object of list items for contextual band. Format: { link-label: link-href }
         */
        "contextualLinks": string | object;
        /**
          * Display mode of the footer
         */
        "display": 'compact' | 'full';
        /**
          * Object of list items for sub-footer. Format: { link-label: link-href }
         */
        "subLinks": string | object;
        /**
          * GcdsSignature - The variant of the Government of Canada wordmark
         */
        "wordmarkVariant": 'colour' | 'white';
    }
    interface GcdsGrid {
        /**
          * If total grid size is less than the size of its grid container, this property aligns the grid along the block (column) axis
         */
        "alignContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Aligns grid items along the block (column) axis
         */
        "alignItems"?: 'baseline' | 'center' | 'end' | 'start' | 'stretch';
        /**
          * Defines if grid container is centered or not
         */
        "centered"?: boolean;
        /**
          * Defines the columns of the grid Option to set different layouts for desktop | tablet | default (includes mobile)
         */
        "columns"?: string;
        "columnsDesktop"?: string;
        "columnsTablet"?: string;
        /**
          * Defines grid container size
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines element as grid or inline-grid container
         */
        "display"?: 'grid' | 'inline-grid';
        /**
          * Shorthand for column-gap + row-gap Specifies the width of the gutters between columns and rows
         */
        "gap"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * If total grid size is less than the size of its grid container, this property aligns the grid along the inline (row) axis
         */
        "justifyContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Aligns grid items along the inline (row) axis
         */
        "justifyItems"?: 'center' | 'end' | 'start' | 'stretch';
        /**
          * Sets both the align-content + justify-content properties
         */
        "placeContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Sets both the align-items + justify-items properties
         */
        "placeItems"?: 'center' | 'end' | 'start' | 'stretch';
        /**
          * Set tag for grid container
         */
        "tag"?: string;
    }
    interface GcdsHeader {
        /**
          * GcdsLangToggle - The href attribute specifies the URL of the opposite language page
         */
        "langHref": string;
        /**
          * GcdsSignature - GCDS signature links to Canada.ca
         */
        "signatureHasLink": boolean;
        /**
          * GcdsSignature - The variant of the Government of Canada signature
         */
        "signatureVariant": 'colour' | 'white';
        /**
          * Top navigation - Skip to content href
         */
        "skipToHref": string;
    }
    interface GcdsHint {
        /**
          * Hint displayed below the label and above the input field.
         */
        "hint"?: string;
        /**
          * Id attribute for the hint.
         */
        "hintId": string;
    }
    interface GcdsIcon {
        /**
          * If the icon should render as a fixed-width square, or their natural width.
         */
        "fixedWidth": boolean;
        /**
          * Style of the icon. 'regular' icons are outlined. Some icons have 'solid' variation.
         */
        "iconStyle"?: 'regular' | 'solid';
        /**
          * Add icon description.
         */
        "label"?: string;
        /**
          * Add margin to the left of the icon
         */
        "marginLeft"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * Add margin to the right of the icon
         */
        "marginRight"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * Name of the icon.
         */
        "name": string;
        /**
          * Defines the size of the icon.
         */
        "size"?: 'inherit' | 'caption' | 'text' | 'h6' | 'h5' | 'h4' | 'h3' | 'h2' | 'h1';
    }
    interface GcdsInput {
        /**
          * String to have autocomplete enabled
         */
        "autocomplete"?: 'on' | 'off';
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler": Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid input element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Hint displayed below the label and above the input field.
         */
        "hint"?: string;
        /**
          * Id + name attribute for an input element.
         */
        "inputId": string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Size attribute for an input element. Defines max-length as well.
         */
        "size"?: number;
        /**
          * Set Input types
         */
        "type"?: 'email' | 'number' | 'password' | 'search' | 'text' | 'url';
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Default value for an input element.
         */
        "value"?: string;
    }
    interface GcdsLabel {
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Defines the label's for attribute.
         */
        "labelFor": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
    }
    interface GcdsLangToggle {
        /**
          * The href attribute specifies the URL of the opposite language page
         */
        "href": string;
    }
    interface GcdsMenuGroup {
        "focusTrigger": () => Promise<void>;
        /**
          * heading for the menu group
         */
        "heading": string;
        /**
          * Has the menu group been expanded
         */
        "open": boolean;
        "toggleMenu": () => Promise<void>;
    }
    interface GcdsMenuLink {
        /**
          * Current page flag
         */
        "current": boolean;
        "focusLink": () => Promise<void>;
        /**
          * Link href
         */
        "href": string;
    }
    interface GcdsPagination {
        /**
          * List display - Current page number
         */
        "currentPage": number;
        /**
          * Navigation element label
         */
        "display": "list" | "simple";
        /**
          * Navigation element label
         */
        "label": string;
        /**
          * Simple display - href for next link
         */
        "nextHref": string;
        /**
          * Simple display - lable for next link
         */
        "nextLabel": string;
        /**
          * Function to fire when pageChange event is called
         */
        "pageChangeHandler": Function;
        /**
          * Simple display - href for previous link
         */
        "previousHref": string;
        /**
          * Simple display - label for previous link
         */
        "previousLabel": string;
        /**
          * List display - Total number of pages
         */
        "totalPages": number;
        /**
          * List display - URL object to create query strings and fragment on links
         */
        "url": Object;
    }
    interface GcdsPhaseBanner {
        /**
          * Defines banner role.
         */
        "bannerRole"?: 'primary' | 'secondary';
        /**
          * Defines the container width of the phase banner content
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines if the banner's position is fixed.
         */
        "isFixed"?: boolean;
    }
    interface GcdsRadio {
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Specifies if an input element is checked.
         */
        "checked": boolean;
        /**
          * Custom callback function on click event
         */
        "clickHandler": Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled": boolean;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Hint displayed below the label.
         */
        "hint": string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Name attribute for an input element.
         */
        "name": string;
        /**
          * Id attribute for an input element.
         */
        "radioId": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required": boolean;
        /**
          * Value for an input element.
         */
        "value": string;
    }
    interface GcdsSelect {
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler": Function;
        /**
          * The default value is an optional value that gets displayed before the user selects an option.
         */
        "defaultValue"?: string;
        /**
          * Specifies if a select element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid select element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Hint displayed below the label.
         */
        "hint"?: string;
        /**
          * Form field label.
         */
        "label": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Id attribute for a select element.
         */
        "selectId": string;
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for a select element.
         */
        "value"?: string;
    }
    interface GcdsSidebarMenu {
        /**
          * Label for navigation landmark
         */
        "label": string;
        /**
          * Sticky navigation flag
         */
        "position": 'static' | 'sticky';
        "updateMenuItemQueue": (el: any, includeElement?: boolean) => Promise<void>;
        "updateMenuSize": (size: any) => Promise<void>;
    }
    interface GcdsSignature {
        /**
          * Has link to canada.ca. Only applies to signature
         */
        "hasLink": boolean;
        /**
          * The type of graphic to render
         */
        "type": 'signature' | 'wordmark';
        /**
          * The colour variant to render
         */
        "variant": 'colour' | 'white';
    }
    interface GcdsSiteMenu {
        /**
          * Menu alignment
         */
        "alignment": 'left' | 'center' | 'right' | 'split';
        /**
          * Label for navigation landmark
         */
        "label": string;
        /**
          * Sticky navigation flag
         */
        "position": 'static' | 'sticky';
        "updateMenuItemQueue": (el: any, includeElement?: boolean) => Promise<void>;
        "updateMenuSize": (size: any) => Promise<void>;
    }
    interface GcdsStepper {
        /**
          * Defines the current step.
         */
        "currentStep": number;
        /**
          * Defines the total amount of steps.
         */
        "totalSteps": number;
    }
    interface GcdsTextarea {
        /**
          * Custom callback function on blur event
         */
        "blurHandler": Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler": Function;
        /**
          * Sets the maxlength attribute for the textarea element.
         */
        "characterCount"?: number;
        /**
          * Defines width for textarea cols (the min-width for textarea's is 50%).
         */
        "cols"?: number;
        /**
          * Specifies if a textarea element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid textarea element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler": Function;
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Hint displayed below the label and above the textarea field.
         */
        "hint"?: string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Default value for textarea rows.
         */
        "rows"?: number;
        /**
          * Id + name attribute for a textarea element.
         */
        "textareaId": string;
        /**
          * Call any active validators
         */
        "validate": () => Promise<void>;
        /**
          * Set event to call validator
         */
        "validateOn": 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Default value for an input element.
         */
        "value"?: string;
    }
    interface GcdsVerifyBanner {
        /**
          * Defines the container width of the verify banner content
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines if the banner's position is fixed.
         */
        "isFixed"?: boolean;
    }
}
export interface GcdsAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsAlertElement;
}
export interface GcdsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsButtonElement;
}
export interface GcdsCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsCheckboxElement;
}
export interface GcdsFieldsetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsFieldsetElement;
}
export interface GcdsFileUploaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsFileUploaderElement;
}
export interface GcdsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsInputElement;
}
export interface GcdsMenuGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsMenuGroupElement;
}
export interface GcdsPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsPaginationElement;
}
export interface GcdsRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsRadioElement;
}
export interface GcdsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsSelectElement;
}
export interface GcdsTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGcdsTextareaElement;
}
declare global {
    interface HTMLGcdsAlertElement extends Components.GcdsAlert, HTMLStencilElement {
    }
    var HTMLGcdsAlertElement: {
        prototype: HTMLGcdsAlertElement;
        new (): HTMLGcdsAlertElement;
    };
    interface HTMLGcdsBreadcrumbsElement extends Components.GcdsBreadcrumbs, HTMLStencilElement {
    }
    var HTMLGcdsBreadcrumbsElement: {
        prototype: HTMLGcdsBreadcrumbsElement;
        new (): HTMLGcdsBreadcrumbsElement;
    };
    interface HTMLGcdsBreadcrumbsItemElement extends Components.GcdsBreadcrumbsItem, HTMLStencilElement {
    }
    var HTMLGcdsBreadcrumbsItemElement: {
        prototype: HTMLGcdsBreadcrumbsItemElement;
        new (): HTMLGcdsBreadcrumbsItemElement;
    };
    interface HTMLGcdsButtonElement extends Components.GcdsButton, HTMLStencilElement {
    }
    var HTMLGcdsButtonElement: {
        prototype: HTMLGcdsButtonElement;
        new (): HTMLGcdsButtonElement;
    };
    interface HTMLGcdsCheckboxElement extends Components.GcdsCheckbox, HTMLStencilElement {
    }
    var HTMLGcdsCheckboxElement: {
        prototype: HTMLGcdsCheckboxElement;
        new (): HTMLGcdsCheckboxElement;
    };
    interface HTMLGcdsContainerElement extends Components.GcdsContainer, HTMLStencilElement {
    }
    var HTMLGcdsContainerElement: {
        prototype: HTMLGcdsContainerElement;
        new (): HTMLGcdsContainerElement;
    };
    interface HTMLGcdsDateModifiedElement extends Components.GcdsDateModified, HTMLStencilElement {
    }
    var HTMLGcdsDateModifiedElement: {
        prototype: HTMLGcdsDateModifiedElement;
        new (): HTMLGcdsDateModifiedElement;
    };
    interface HTMLGcdsDetailsElement extends Components.GcdsDetails, HTMLStencilElement {
    }
    var HTMLGcdsDetailsElement: {
        prototype: HTMLGcdsDetailsElement;
        new (): HTMLGcdsDetailsElement;
    };
    interface HTMLGcdsErrorMessageElement extends Components.GcdsErrorMessage, HTMLStencilElement {
    }
    var HTMLGcdsErrorMessageElement: {
        prototype: HTMLGcdsErrorMessageElement;
        new (): HTMLGcdsErrorMessageElement;
    };
    interface HTMLGcdsErrorSummaryElement extends Components.GcdsErrorSummary, HTMLStencilElement {
    }
    var HTMLGcdsErrorSummaryElement: {
        prototype: HTMLGcdsErrorSummaryElement;
        new (): HTMLGcdsErrorSummaryElement;
    };
    interface HTMLGcdsFieldsetElement extends Components.GcdsFieldset, HTMLStencilElement {
    }
    var HTMLGcdsFieldsetElement: {
        prototype: HTMLGcdsFieldsetElement;
        new (): HTMLGcdsFieldsetElement;
    };
    interface HTMLGcdsFileUploaderElement extends Components.GcdsFileUploader, HTMLStencilElement {
    }
    var HTMLGcdsFileUploaderElement: {
        prototype: HTMLGcdsFileUploaderElement;
        new (): HTMLGcdsFileUploaderElement;
    };
    interface HTMLGcdsFooterElement extends Components.GcdsFooter, HTMLStencilElement {
    }
    var HTMLGcdsFooterElement: {
        prototype: HTMLGcdsFooterElement;
        new (): HTMLGcdsFooterElement;
    };
    interface HTMLGcdsGridElement extends Components.GcdsGrid, HTMLStencilElement {
    }
    var HTMLGcdsGridElement: {
        prototype: HTMLGcdsGridElement;
        new (): HTMLGcdsGridElement;
    };
    interface HTMLGcdsHeaderElement extends Components.GcdsHeader, HTMLStencilElement {
    }
    var HTMLGcdsHeaderElement: {
        prototype: HTMLGcdsHeaderElement;
        new (): HTMLGcdsHeaderElement;
    };
    interface HTMLGcdsHintElement extends Components.GcdsHint, HTMLStencilElement {
    }
    var HTMLGcdsHintElement: {
        prototype: HTMLGcdsHintElement;
        new (): HTMLGcdsHintElement;
    };
    interface HTMLGcdsIconElement extends Components.GcdsIcon, HTMLStencilElement {
    }
    var HTMLGcdsIconElement: {
        prototype: HTMLGcdsIconElement;
        new (): HTMLGcdsIconElement;
    };
    interface HTMLGcdsInputElement extends Components.GcdsInput, HTMLStencilElement {
    }
    var HTMLGcdsInputElement: {
        prototype: HTMLGcdsInputElement;
        new (): HTMLGcdsInputElement;
    };
    interface HTMLGcdsLabelElement extends Components.GcdsLabel, HTMLStencilElement {
    }
    var HTMLGcdsLabelElement: {
        prototype: HTMLGcdsLabelElement;
        new (): HTMLGcdsLabelElement;
    };
    interface HTMLGcdsLangToggleElement extends Components.GcdsLangToggle, HTMLStencilElement {
    }
    var HTMLGcdsLangToggleElement: {
        prototype: HTMLGcdsLangToggleElement;
        new (): HTMLGcdsLangToggleElement;
    };
    interface HTMLGcdsMenuGroupElement extends Components.GcdsMenuGroup, HTMLStencilElement {
    }
    var HTMLGcdsMenuGroupElement: {
        prototype: HTMLGcdsMenuGroupElement;
        new (): HTMLGcdsMenuGroupElement;
    };
    interface HTMLGcdsMenuLinkElement extends Components.GcdsMenuLink, HTMLStencilElement {
    }
    var HTMLGcdsMenuLinkElement: {
        prototype: HTMLGcdsMenuLinkElement;
        new (): HTMLGcdsMenuLinkElement;
    };
    interface HTMLGcdsPaginationElement extends Components.GcdsPagination, HTMLStencilElement {
    }
    var HTMLGcdsPaginationElement: {
        prototype: HTMLGcdsPaginationElement;
        new (): HTMLGcdsPaginationElement;
    };
    interface HTMLGcdsPhaseBannerElement extends Components.GcdsPhaseBanner, HTMLStencilElement {
    }
    var HTMLGcdsPhaseBannerElement: {
        prototype: HTMLGcdsPhaseBannerElement;
        new (): HTMLGcdsPhaseBannerElement;
    };
    interface HTMLGcdsRadioElement extends Components.GcdsRadio, HTMLStencilElement {
    }
    var HTMLGcdsRadioElement: {
        prototype: HTMLGcdsRadioElement;
        new (): HTMLGcdsRadioElement;
    };
    interface HTMLGcdsSelectElement extends Components.GcdsSelect, HTMLStencilElement {
    }
    var HTMLGcdsSelectElement: {
        prototype: HTMLGcdsSelectElement;
        new (): HTMLGcdsSelectElement;
    };
    interface HTMLGcdsSidebarMenuElement extends Components.GcdsSidebarMenu, HTMLStencilElement {
    }
    var HTMLGcdsSidebarMenuElement: {
        prototype: HTMLGcdsSidebarMenuElement;
        new (): HTMLGcdsSidebarMenuElement;
    };
    interface HTMLGcdsSignatureElement extends Components.GcdsSignature, HTMLStencilElement {
    }
    var HTMLGcdsSignatureElement: {
        prototype: HTMLGcdsSignatureElement;
        new (): HTMLGcdsSignatureElement;
    };
    interface HTMLGcdsSiteMenuElement extends Components.GcdsSiteMenu, HTMLStencilElement {
    }
    var HTMLGcdsSiteMenuElement: {
        prototype: HTMLGcdsSiteMenuElement;
        new (): HTMLGcdsSiteMenuElement;
    };
    interface HTMLGcdsStepperElement extends Components.GcdsStepper, HTMLStencilElement {
    }
    var HTMLGcdsStepperElement: {
        prototype: HTMLGcdsStepperElement;
        new (): HTMLGcdsStepperElement;
    };
    interface HTMLGcdsTextareaElement extends Components.GcdsTextarea, HTMLStencilElement {
    }
    var HTMLGcdsTextareaElement: {
        prototype: HTMLGcdsTextareaElement;
        new (): HTMLGcdsTextareaElement;
    };
    interface HTMLGcdsVerifyBannerElement extends Components.GcdsVerifyBanner, HTMLStencilElement {
    }
    var HTMLGcdsVerifyBannerElement: {
        prototype: HTMLGcdsVerifyBannerElement;
        new (): HTMLGcdsVerifyBannerElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-alert": HTMLGcdsAlertElement;
        "gcds-breadcrumbs": HTMLGcdsBreadcrumbsElement;
        "gcds-breadcrumbs-item": HTMLGcdsBreadcrumbsItemElement;
        "gcds-button": HTMLGcdsButtonElement;
        "gcds-checkbox": HTMLGcdsCheckboxElement;
        "gcds-container": HTMLGcdsContainerElement;
        "gcds-date-modified": HTMLGcdsDateModifiedElement;
        "gcds-details": HTMLGcdsDetailsElement;
        "gcds-error-message": HTMLGcdsErrorMessageElement;
        "gcds-error-summary": HTMLGcdsErrorSummaryElement;
        "gcds-fieldset": HTMLGcdsFieldsetElement;
        "gcds-file-uploader": HTMLGcdsFileUploaderElement;
        "gcds-footer": HTMLGcdsFooterElement;
        "gcds-grid": HTMLGcdsGridElement;
        "gcds-header": HTMLGcdsHeaderElement;
        "gcds-hint": HTMLGcdsHintElement;
        "gcds-icon": HTMLGcdsIconElement;
        "gcds-input": HTMLGcdsInputElement;
        "gcds-label": HTMLGcdsLabelElement;
        "gcds-lang-toggle": HTMLGcdsLangToggleElement;
        "gcds-menu-group": HTMLGcdsMenuGroupElement;
        "gcds-menu-link": HTMLGcdsMenuLinkElement;
        "gcds-pagination": HTMLGcdsPaginationElement;
        "gcds-phase-banner": HTMLGcdsPhaseBannerElement;
        "gcds-radio": HTMLGcdsRadioElement;
        "gcds-select": HTMLGcdsSelectElement;
        "gcds-sidebar-menu": HTMLGcdsSidebarMenuElement;
        "gcds-signature": HTMLGcdsSignatureElement;
        "gcds-site-menu": HTMLGcdsSiteMenuElement;
        "gcds-stepper": HTMLGcdsStepperElement;
        "gcds-textarea": HTMLGcdsTextareaElement;
        "gcds-verify-banner": HTMLGcdsVerifyBannerElement;
    }
}
declare namespace LocalJSX {
    interface GcdsAlert {
        /**
          * Defines alert role.
         */
        "alertRole"?: 'danger' | 'info' | 'success' | 'warning';
        /**
          * Defines the max width of the alert content.
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Callback when the close button is clicked.
         */
        "dismissHandler"?: Function;
        /**
          * Defines the alert heading.
         */
        "heading": string;
        /**
          * Defines if the alert's close button is displayed or not.
         */
        "hideCloseBtn"?: boolean;
        /**
          * Defines if the alert's role icon is displayed or not.
         */
        "hideRoleIcon"?: boolean;
        /**
          * Defines if the alert's position is fixed.
         */
        "isFixed"?: boolean;
        /**
          * Events
         */
        "onGcdsDismiss"?: (event: GcdsAlertCustomEvent<void>) => void;
    }
    interface GcdsBreadcrumbs {
        /**
          * Defines if the default canada.ca link should be displayed or not.
         */
        "hideCanadaLink"?: boolean;
    }
    interface GcdsBreadcrumbsItem {
        /**
          * Specifies the href of the breadcrumb item.
         */
        "href": string | undefined;
    }
    interface GcdsButton {
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * The buttonId attribute specifies the id for a <button> element.
         */
        "buttonId"?: string;
        /**
          * Set the main style
         */
        "buttonRole"?: 'primary' | 'secondary' | 'danger' | 'skip-to-content';
        /**
          * Set the style variant
         */
        "buttonStyle"?: 'solid' | 'text-only';
        /**
          * Custom callback function on click event
         */
        "clickHandler"?: Function;
        /**
          * The disabled attribute for a <button> element.
         */
        "disabled"?: boolean;
        /**
          * The download attribute specifies that the target (the file specified in the href attribute) will be downloaded when a user clicks on the hyperlink
         */
        "download"?: string | undefined;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * The href attribute specifies the URL of the page the link goes to
         */
        "href"?: string | undefined;
        /**
          * The name attribute specifies the name for a <button> element.
         */
        "name"?: string | undefined;
        /**
          * Emitted when the button loses focus.
         */
        "onGcdsBlur"?: (event: GcdsButtonCustomEvent<void>) => void;
        /**
          * Emitted when the button has focus.
         */
        "onGcdsFocus"?: (event: GcdsButtonCustomEvent<void>) => void;
        /**
          * The rel attribute specifies the relationship between the current document and the linked document
         */
        "rel"?: string | undefined;
        /**
          * Set the button size
         */
        "size"?: 'regular' | 'small';
        /**
          * The target attribute specifies where to open the linked document
         */
        "target"?: string | undefined;
        /**
          * Set button types
         */
        "type"?: 'submit' | 'reset' | 'button' | 'link';
    }
    interface GcdsCheckbox {
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Id attribute for an input element.
         */
        "checkboxId": string;
        /**
          * Specifies if an input element is checked.
         */
        "checked"?: boolean;
        /**
          * Custom callback function on click event
         */
        "clickHandler"?: Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid input element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Hint displayed below the label.
         */
        "hint"?: string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Name attribute for an input element.
         */
        "name": string;
        /**
          * Emitted when the checkbox loses focus.
         */
        "onGcdsBlur"?: (event: GcdsCheckboxCustomEvent<void>) => void;
        /**
          * Update value based on user input.
         */
        "onGcdsChange"?: (event: GcdsCheckboxCustomEvent<any>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsError"?: (event: GcdsCheckboxCustomEvent<object>) => void;
        /**
          * Emitted when the checkbox has focus.
         */
        "onGcdsFocus"?: (event: GcdsCheckboxCustomEvent<void>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsValid"?: (event: GcdsCheckboxCustomEvent<object>) => void;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for an input element.
         */
        "value"?: string;
    }
    interface GcdsContainer {
        /**
          * Defines if container is centered or not
         */
        "centered"?: boolean;
        /**
          * Defines container size
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Set tag for container
         */
        "tag"?: string;
    }
    interface GcdsDateModified {
    }
    interface GcdsDetails {
        /**
          * The details title summarizes the panel content.
         */
        "detailsTitle": string;
        /**
          * Defines if the details panel is open by default or not.
         */
        "open"?: boolean;
    }
    interface GcdsErrorMessage {
        /**
          * Error message for an invalid form field.
         */
        "message": string;
        /**
          * Id attribute for the error message.
         */
        "messageId": string;
    }
    interface GcdsErrorSummary {
        /**
          * Object of list items for error list. Format: { link-href: link-label }
         */
        "errorLinks"?: string | object;
        /**
          * Set error summary heading
         */
        "heading"?: string;
        /**
          * Specifies if the error summary should listen for GcdsError event to generate error list.
         */
        "listen"?: boolean;
        /**
          * Set error summary message
         */
        "subHeading"?: string;
    }
    interface GcdsFieldset {
        /**
          * Flag to disable fieldset and its contents
         */
        "disabled"?: boolean;
        /**
          * Error message for invalid form elements in group.
         */
        "errorMessage"?: string;
        /**
          * The unique identifier for the component
         */
        "fieldsetId": string;
        /**
          * Hint displayed below the legend.
         */
        "hint"?: string;
        /**
          * The title for the contents of the fieldset
         */
        "legend": string;
        /**
          * Emitted when the fieldset has a validation error.
         */
        "onGcdsError"?: (event: GcdsFieldsetCustomEvent<object>) => void;
        /**
          * Emitted when the fieldset has a validation error.
         */
        "onGcdsGroupError"?: (event: GcdsFieldsetCustomEvent<string>) => void;
        /**
          * Emitted when the fieldset has a validation error.
         */
        "onGcdsGroupErrorClear"?: (event: GcdsFieldsetCustomEvent<void>) => void;
        /**
          * Emitted when the fieldset has a validation error.
         */
        "onGcdsValid"?: (event: GcdsFieldsetCustomEvent<object>) => void;
        /**
          * Flag the contents are required
         */
        "required"?: boolean;
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
    }
    interface GcdsFileUploader {
        /**
          * Defines the file types the file uploader accepts.
         */
        "accept"?: string;
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler"?: Function;
        /**
          * Specifies if a file uploader element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid file uploader element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Hint displayed below the label.
         */
        "hint"?: string;
        /**
          * Form field label.
         */
        "label": string;
        /**
          * Boolean that specifies if the user is allowed to select more than one file.
         */
        "multiple"?: boolean;
        /**
          * Emitted when the uploader loses focus.
         */
        "onGcdsBlur"?: (event: GcdsFileUploaderCustomEvent<void>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsError"?: (event: GcdsFileUploaderCustomEvent<object>) => void;
        /**
          * Update value based on user selection.
         */
        "onGcdsFileUploaderChange"?: (event: GcdsFileUploaderCustomEvent<any>) => void;
        /**
          * Emitted when the uploader has focus.
         */
        "onGcdsFocus"?: (event: GcdsFileUploaderCustomEvent<void>) => void;
        /**
          * Remove file and update value.
         */
        "onGcdsRemoveFile"?: (event: GcdsFileUploaderCustomEvent<any>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsValid"?: (event: GcdsFileUploaderCustomEvent<object>) => void;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Id attribute for a file uploader element.
         */
        "uploaderId": string;
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for a file uploader element.
         */
        "value"?: string[];
    }
    interface GcdsFooter {
        /**
          * Heading for contextual slot and nav landmark
         */
        "contextualHeading"?: string;
        /**
          * Object of list items for contextual band. Format: { link-label: link-href }
         */
        "contextualLinks"?: string | object;
        /**
          * Display mode of the footer
         */
        "display": 'compact' | 'full';
        /**
          * Object of list items for sub-footer. Format: { link-label: link-href }
         */
        "subLinks"?: string | object;
        /**
          * GcdsSignature - The variant of the Government of Canada wordmark
         */
        "wordmarkVariant"?: 'colour' | 'white';
    }
    interface GcdsGrid {
        /**
          * If total grid size is less than the size of its grid container, this property aligns the grid along the block (column) axis
         */
        "alignContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Aligns grid items along the block (column) axis
         */
        "alignItems"?: 'baseline' | 'center' | 'end' | 'start' | 'stretch';
        /**
          * Defines if grid container is centered or not
         */
        "centered"?: boolean;
        /**
          * Defines the columns of the grid Option to set different layouts for desktop | tablet | default (includes mobile)
         */
        "columns"?: string;
        "columnsDesktop"?: string;
        "columnsTablet"?: string;
        /**
          * Defines grid container size
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines element as grid or inline-grid container
         */
        "display"?: 'grid' | 'inline-grid';
        /**
          * Shorthand for column-gap + row-gap Specifies the width of the gutters between columns and rows
         */
        "gap"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * If total grid size is less than the size of its grid container, this property aligns the grid along the inline (row) axis
         */
        "justifyContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Aligns grid items along the inline (row) axis
         */
        "justifyItems"?: 'center' | 'end' | 'start' | 'stretch';
        /**
          * Sets both the align-content + justify-content properties
         */
        "placeContent"?: 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start' | 'stretch';
        /**
          * Sets both the align-items + justify-items properties
         */
        "placeItems"?: 'center' | 'end' | 'start' | 'stretch';
        /**
          * Set tag for grid container
         */
        "tag"?: string;
    }
    interface GcdsHeader {
        /**
          * GcdsLangToggle - The href attribute specifies the URL of the opposite language page
         */
        "langHref": string;
        /**
          * GcdsSignature - GCDS signature links to Canada.ca
         */
        "signatureHasLink"?: boolean;
        /**
          * GcdsSignature - The variant of the Government of Canada signature
         */
        "signatureVariant"?: 'colour' | 'white';
        /**
          * Top navigation - Skip to content href
         */
        "skipToHref": string;
    }
    interface GcdsHint {
        /**
          * Hint displayed below the label and above the input field.
         */
        "hint"?: string;
        /**
          * Id attribute for the hint.
         */
        "hintId"?: string;
    }
    interface GcdsIcon {
        /**
          * If the icon should render as a fixed-width square, or their natural width.
         */
        "fixedWidth"?: boolean;
        /**
          * Style of the icon. 'regular' icons are outlined. Some icons have 'solid' variation.
         */
        "iconStyle"?: 'regular' | 'solid';
        /**
          * Add icon description.
         */
        "label"?: string;
        /**
          * Add margin to the left of the icon
         */
        "marginLeft"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * Add margin to the right of the icon
         */
        "marginRight"?: '0' | '50' | '100' | '150' | '200' | '250' | '300' | '400' | '450' | '500' | '550' | '600' | '700' | '800' | '900' | '1000';
        /**
          * Name of the icon.
         */
        "name": string;
        /**
          * Defines the size of the icon.
         */
        "size"?: 'inherit' | 'caption' | 'text' | 'h6' | 'h5' | 'h4' | 'h3' | 'h2' | 'h1';
    }
    interface GcdsInput {
        /**
          * String to have autocomplete enabled
         */
        "autocomplete"?: 'on' | 'off';
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler"?: Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid input element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Hint displayed below the label and above the input field.
         */
        "hint"?: string;
        /**
          * Id + name attribute for an input element.
         */
        "inputId": string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Emitted when the input loses focus.
         */
        "onGcdsBlur"?: (event: GcdsInputCustomEvent<void>) => void;
        /**
          * Update value based on user input.
         */
        "onGcdsChange"?: (event: GcdsInputCustomEvent<any>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsError"?: (event: GcdsInputCustomEvent<object>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onGcdsFocus"?: (event: GcdsInputCustomEvent<void>) => void;
        /**
          * Emitted when the input has a validation error.
         */
        "onGcdsValid"?: (event: GcdsInputCustomEvent<object>) => void;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Size attribute for an input element. Defines max-length as well.
         */
        "size"?: number;
        /**
          * Set Input types
         */
        "type"?: 'email' | 'number' | 'password' | 'search' | 'text' | 'url';
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Default value for an input element.
         */
        "value"?: string;
    }
    interface GcdsLabel {
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Form field label
         */
        "label"?: string;
        /**
          * Defines the label's for attribute.
         */
        "labelFor"?: string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
    }
    interface GcdsLangToggle {
        /**
          * The href attribute specifies the URL of the opposite language page
         */
        "href": string;
    }
    interface GcdsMenuGroup {
        /**
          * heading for the menu group
         */
        "heading": string;
        /**
          * Emitted when the button has focus.
         */
        "onGcdsClick"?: (event: GcdsMenuGroupCustomEvent<void>) => void;
        /**
          * Has the menu group been expanded
         */
        "open"?: boolean;
    }
    interface GcdsMenuLink {
        /**
          * Current page flag
         */
        "current"?: boolean;
        /**
          * Link href
         */
        "href": string;
    }
    interface GcdsPagination {
        /**
          * List display - Current page number
         */
        "currentPage"?: number;
        /**
          * Navigation element label
         */
        "display"?: "list" | "simple";
        /**
          * Navigation element label
         */
        "label": string;
        /**
          * Simple display - href for next link
         */
        "nextHref"?: string;
        /**
          * Simple display - lable for next link
         */
        "nextLabel"?: string;
        /**
          * Update value based on user input.
         */
        "onGcdsPageChange"?: (event: GcdsPaginationCustomEvent<void>) => void;
        /**
          * Function to fire when pageChange event is called
         */
        "pageChangeHandler"?: Function;
        /**
          * Simple display - href for previous link
         */
        "previousHref"?: string;
        /**
          * Simple display - label for previous link
         */
        "previousLabel"?: string;
        /**
          * List display - Total number of pages
         */
        "totalPages"?: number;
        /**
          * List display - URL object to create query strings and fragment on links
         */
        "url"?: Object;
    }
    interface GcdsPhaseBanner {
        /**
          * Defines banner role.
         */
        "bannerRole"?: 'primary' | 'secondary';
        /**
          * Defines the container width of the phase banner content
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines if the banner's position is fixed.
         */
        "isFixed"?: boolean;
    }
    interface GcdsRadio {
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Specifies if an input element is checked.
         */
        "checked"?: boolean;
        /**
          * Custom callback function on click event
         */
        "clickHandler"?: Function;
        /**
          * Specifies if an input element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Hint displayed below the label.
         */
        "hint"?: string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Name attribute for an input element.
         */
        "name": string;
        /**
          * Emitted when the radio loses focus.
         */
        "onGcdsBlur"?: (event: GcdsRadioCustomEvent<void>) => void;
        /**
          * Emitted when the radio has focus.
         */
        "onGcdsFocus"?: (event: GcdsRadioCustomEvent<void>) => void;
        /**
          * Emitted when the radio button is checked
         */
        "onGcdsRadioChange"?: (event: GcdsRadioCustomEvent<void>) => void;
        /**
          * Id attribute for an input element.
         */
        "radioId": string;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Value for an input element.
         */
        "value"?: string;
    }
    interface GcdsSelect {
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler"?: Function;
        /**
          * The default value is an optional value that gets displayed before the user selects an option.
         */
        "defaultValue"?: string;
        /**
          * Specifies if a select element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid select element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Hint displayed below the label.
         */
        "hint"?: string;
        /**
          * Form field label.
         */
        "label": string;
        /**
          * Emitted when the select loses focus.
         */
        "onGcdsBlur"?: (event: GcdsSelectCustomEvent<void>) => void;
        /**
          * Emitted when the select has a validation error.
         */
        "onGcdsError"?: (event: GcdsSelectCustomEvent<object>) => void;
        /**
          * Emitted when the select has focus.
         */
        "onGcdsFocus"?: (event: GcdsSelectCustomEvent<void>) => void;
        /**
          * Update value based on user selection.
         */
        "onGcdsSelectChange"?: (event: GcdsSelectCustomEvent<any>) => void;
        /**
          * Emitted when the select has a validation error.
         */
        "onGcdsValid"?: (event: GcdsSelectCustomEvent<object>) => void;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Id attribute for a select element.
         */
        "selectId": string;
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Value for a select element.
         */
        "value"?: string;
    }
    interface GcdsSidebarMenu {
        /**
          * Label for navigation landmark
         */
        "label"?: string;
        /**
          * Sticky navigation flag
         */
        "position"?: 'static' | 'sticky';
    }
    interface GcdsSignature {
        /**
          * Has link to canada.ca. Only applies to signature
         */
        "hasLink"?: boolean;
        /**
          * The type of graphic to render
         */
        "type"?: 'signature' | 'wordmark';
        /**
          * The colour variant to render
         */
        "variant"?: 'colour' | 'white';
    }
    interface GcdsSiteMenu {
        /**
          * Menu alignment
         */
        "alignment"?: 'left' | 'center' | 'right' | 'split';
        /**
          * Label for navigation landmark
         */
        "label"?: string;
        /**
          * Sticky navigation flag
         */
        "position"?: 'static' | 'sticky';
    }
    interface GcdsStepper {
        /**
          * Defines the current step.
         */
        "currentStep": number;
        /**
          * Defines the total amount of steps.
         */
        "totalSteps": number;
    }
    interface GcdsTextarea {
        /**
          * Custom callback function on blur event
         */
        "blurHandler"?: Function;
        /**
          * Custom callback function on change event
         */
        "changeHandler"?: Function;
        /**
          * Sets the maxlength attribute for the textarea element.
         */
        "characterCount"?: number;
        /**
          * Defines width for textarea cols (the min-width for textarea's is 50%).
         */
        "cols"?: number;
        /**
          * Specifies if a textarea element is disabled or not.
         */
        "disabled"?: boolean;
        /**
          * Error message for an invalid textarea element.
         */
        "errorMessage"?: string;
        /**
          * Custom callback function on focus event
         */
        "focusHandler"?: Function;
        /**
          * Specifies if the label is hidden or not.
         */
        "hideLabel"?: boolean;
        /**
          * Hint displayed below the label and above the textarea field.
         */
        "hint"?: string;
        /**
          * Form field label
         */
        "label": string;
        /**
          * Emitted when the textarea loses focus.
         */
        "onGcdsBlur"?: (event: GcdsTextareaCustomEvent<void>) => void;
        /**
          * Update value based on user input.
         */
        "onGcdsChange"?: (event: GcdsTextareaCustomEvent<any>) => void;
        /**
          * Emitted when the textarea has a validation error.
         */
        "onGcdsError"?: (event: GcdsTextareaCustomEvent<object>) => void;
        /**
          * Emitted when the textarea has focus.
         */
        "onGcdsFocus"?: (event: GcdsTextareaCustomEvent<void>) => void;
        /**
          * Emitted when the textarea has a validation error.
         */
        "onGcdsValid"?: (event: GcdsTextareaCustomEvent<object>) => void;
        /**
          * Specifies if a form field is required or not.
         */
        "required"?: boolean;
        /**
          * Default value for textarea rows.
         */
        "rows"?: number;
        /**
          * Id + name attribute for a textarea element.
         */
        "textareaId": string;
        /**
          * Set event to call validator
         */
        "validateOn"?: 'blur' | 'submit' | 'other';
        /**
          * Array of validators
         */
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        /**
          * Default value for an input element.
         */
        "value"?: string;
    }
    interface GcdsVerifyBanner {
        /**
          * Defines the container width of the verify banner content
         */
        "container"?: 'full' | 'xl' | 'lg' | 'md' | 'sm' | 'xs';
        /**
          * Defines if the banner's position is fixed.
         */
        "isFixed"?: boolean;
    }
    interface IntrinsicElements {
        "gcds-alert": GcdsAlert;
        "gcds-breadcrumbs": GcdsBreadcrumbs;
        "gcds-breadcrumbs-item": GcdsBreadcrumbsItem;
        "gcds-button": GcdsButton;
        "gcds-checkbox": GcdsCheckbox;
        "gcds-container": GcdsContainer;
        "gcds-date-modified": GcdsDateModified;
        "gcds-details": GcdsDetails;
        "gcds-error-message": GcdsErrorMessage;
        "gcds-error-summary": GcdsErrorSummary;
        "gcds-fieldset": GcdsFieldset;
        "gcds-file-uploader": GcdsFileUploader;
        "gcds-footer": GcdsFooter;
        "gcds-grid": GcdsGrid;
        "gcds-header": GcdsHeader;
        "gcds-hint": GcdsHint;
        "gcds-icon": GcdsIcon;
        "gcds-input": GcdsInput;
        "gcds-label": GcdsLabel;
        "gcds-lang-toggle": GcdsLangToggle;
        "gcds-menu-group": GcdsMenuGroup;
        "gcds-menu-link": GcdsMenuLink;
        "gcds-pagination": GcdsPagination;
        "gcds-phase-banner": GcdsPhaseBanner;
        "gcds-radio": GcdsRadio;
        "gcds-select": GcdsSelect;
        "gcds-sidebar-menu": GcdsSidebarMenu;
        "gcds-signature": GcdsSignature;
        "gcds-site-menu": GcdsSiteMenu;
        "gcds-stepper": GcdsStepper;
        "gcds-textarea": GcdsTextarea;
        "gcds-verify-banner": GcdsVerifyBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcds-alert": LocalJSX.GcdsAlert & JSXBase.HTMLAttributes<HTMLGcdsAlertElement>;
            "gcds-breadcrumbs": LocalJSX.GcdsBreadcrumbs & JSXBase.HTMLAttributes<HTMLGcdsBreadcrumbsElement>;
            "gcds-breadcrumbs-item": LocalJSX.GcdsBreadcrumbsItem & JSXBase.HTMLAttributes<HTMLGcdsBreadcrumbsItemElement>;
            "gcds-button": LocalJSX.GcdsButton & JSXBase.HTMLAttributes<HTMLGcdsButtonElement>;
            "gcds-checkbox": LocalJSX.GcdsCheckbox & JSXBase.HTMLAttributes<HTMLGcdsCheckboxElement>;
            "gcds-container": LocalJSX.GcdsContainer & JSXBase.HTMLAttributes<HTMLGcdsContainerElement>;
            "gcds-date-modified": LocalJSX.GcdsDateModified & JSXBase.HTMLAttributes<HTMLGcdsDateModifiedElement>;
            "gcds-details": LocalJSX.GcdsDetails & JSXBase.HTMLAttributes<HTMLGcdsDetailsElement>;
            "gcds-error-message": LocalJSX.GcdsErrorMessage & JSXBase.HTMLAttributes<HTMLGcdsErrorMessageElement>;
            "gcds-error-summary": LocalJSX.GcdsErrorSummary & JSXBase.HTMLAttributes<HTMLGcdsErrorSummaryElement>;
            "gcds-fieldset": LocalJSX.GcdsFieldset & JSXBase.HTMLAttributes<HTMLGcdsFieldsetElement>;
            "gcds-file-uploader": LocalJSX.GcdsFileUploader & JSXBase.HTMLAttributes<HTMLGcdsFileUploaderElement>;
            "gcds-footer": LocalJSX.GcdsFooter & JSXBase.HTMLAttributes<HTMLGcdsFooterElement>;
            "gcds-grid": LocalJSX.GcdsGrid & JSXBase.HTMLAttributes<HTMLGcdsGridElement>;
            "gcds-header": LocalJSX.GcdsHeader & JSXBase.HTMLAttributes<HTMLGcdsHeaderElement>;
            "gcds-hint": LocalJSX.GcdsHint & JSXBase.HTMLAttributes<HTMLGcdsHintElement>;
            "gcds-icon": LocalJSX.GcdsIcon & JSXBase.HTMLAttributes<HTMLGcdsIconElement>;
            "gcds-input": LocalJSX.GcdsInput & JSXBase.HTMLAttributes<HTMLGcdsInputElement>;
            "gcds-label": LocalJSX.GcdsLabel & JSXBase.HTMLAttributes<HTMLGcdsLabelElement>;
            "gcds-lang-toggle": LocalJSX.GcdsLangToggle & JSXBase.HTMLAttributes<HTMLGcdsLangToggleElement>;
            "gcds-menu-group": LocalJSX.GcdsMenuGroup & JSXBase.HTMLAttributes<HTMLGcdsMenuGroupElement>;
            "gcds-menu-link": LocalJSX.GcdsMenuLink & JSXBase.HTMLAttributes<HTMLGcdsMenuLinkElement>;
            "gcds-pagination": LocalJSX.GcdsPagination & JSXBase.HTMLAttributes<HTMLGcdsPaginationElement>;
            "gcds-phase-banner": LocalJSX.GcdsPhaseBanner & JSXBase.HTMLAttributes<HTMLGcdsPhaseBannerElement>;
            "gcds-radio": LocalJSX.GcdsRadio & JSXBase.HTMLAttributes<HTMLGcdsRadioElement>;
            "gcds-select": LocalJSX.GcdsSelect & JSXBase.HTMLAttributes<HTMLGcdsSelectElement>;
            "gcds-sidebar-menu": LocalJSX.GcdsSidebarMenu & JSXBase.HTMLAttributes<HTMLGcdsSidebarMenuElement>;
            "gcds-signature": LocalJSX.GcdsSignature & JSXBase.HTMLAttributes<HTMLGcdsSignatureElement>;
            "gcds-site-menu": LocalJSX.GcdsSiteMenu & JSXBase.HTMLAttributes<HTMLGcdsSiteMenuElement>;
            "gcds-stepper": LocalJSX.GcdsStepper & JSXBase.HTMLAttributes<HTMLGcdsStepperElement>;
            "gcds-textarea": LocalJSX.GcdsTextarea & JSXBase.HTMLAttributes<HTMLGcdsTextareaElement>;
            "gcds-verify-banner": LocalJSX.GcdsVerifyBanner & JSXBase.HTMLAttributes<HTMLGcdsVerifyBannerElement>;
        }
    }
}
