
import * as d from './components';

export const DIRECTIVES = [
  d.GcdsAlert,
  d.GcdsBreadcrumbs,
  d.GcdsBreadcrumbsItem,
  d.GcdsButton,
  d.GcdsCheckbox,
  d.GcdsContainer,
  d.GcdsDateModified,
  d.GcdsDetails,
  d.GcdsErrorMessage,
  d.GcdsErrorSummary,
  d.GcdsFieldset,
  d.GcdsFileUploader,
  d.GcdsFooter,
  d.GcdsGrid,
  d.GcdsHeader,
  d.GcdsHint,
  d.GcdsIcon,
  d.GcdsInput,
  d.GcdsLabel,
  d.GcdsLangToggle,
  d.GcdsMenuGroup,
  d.GcdsMenuLink,
  d.GcdsPagination,
  d.GcdsPhaseBanner,
  d.GcdsRadio,
  d.GcdsSelect,
  d.GcdsSidebarMenu,
  d.GcdsSignature,
  d.GcdsSiteMenu,
  d.GcdsSiteMenu1,
  d.GcdsStepper,
  d.GcdsTextarea,
  d.GcdsVerifyBanner
];
