
import * as d from './components';

export const DIRECTIVES = [
  d.GcdsAlert,
  d.GcdsBreadcrumbs,
  d.GcdsBreadcrumbsItem,
  d.GcdsButton,
  d.GcdsCard,
  d.GcdsCheckbox,
  d.GcdsContainer,
  d.GcdsDateModified,
  d.GcdsDetails,
  d.GcdsErrorMessage,
  d.GcdsErrorSummary,
  d.GcdsFieldset,
  d.GcdsFileUploader,
  d.GcdsFooter,
  d.GcdsGrid,
  d.GcdsHeader,
  d.GcdsHeading,
  d.GcdsHint,
  d.GcdsIcon,
  d.GcdsInput,
  d.GcdsLabel,
  d.GcdsLangToggle,
  d.GcdsNavGroup,
  d.GcdsNavLink,
  d.GcdsPagination,
  d.GcdsPhaseBanner,
  d.GcdsRadio,
  d.GcdsSearch,
  d.GcdsSelect,
  d.GcdsSideNav,
  d.GcdsSignature,
  d.GcdsSrOnly,
  d.GcdsStepper,
  d.GcdsText,
  d.GcdsTextarea,
  d.GcdsTopNav,
  d.GcdsTopicMenu,
  d.GcdsVerifyBanner
];
