/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcdsButton {
        /**
          * Set the main style
         */
        "buttonRole": 'primary' | 'secondary' | 'danger' | 'skip-to-content';
        /**
          * Set the style variant
         */
        "buttonStyle": 'solid' | 'outline' | 'text-only';
        /**
          * Set button types
         */
        "buttonType": 'submit' | 'reset' | 'button' | 'link';
        /**
          * StyleAPI: custom background color.
         */
        "customBackgroundColor": string | undefined;
        /**
          * StyleAPI: custom border color.
         */
        "customBorderColor": string | undefined;
        /**
          * StyleAPI: custom border style.
         */
        "customBorderStyle": string | undefined;
        /**
          * StyleAPI: custom border weight.
         */
        "customBorderWeight": string | undefined;
        /**
          * StyleAPI: custom box shadow.
         */
        "customBoxShadow": string | undefined;
        /**
          * StyleAPI: custom btext transform.
         */
        "customCapitalization": string | undefined;
        /**
          * StyleAPI: custom display.
         */
        "customDisplay": string | undefined;
        /**
          * StyleAPI: custom margin.
         */
        "customMargin": string | undefined;
        /**
          * The download attribute specifies that the target (the file specified in the href attribute) will be downloaded when a user clicks on the hyperlink
         */
        "download": string | undefined;
        /**
          * Focus element
         */
        "focusElement": () => Promise<void>;
        /**
          * The href attribute specifies the URL of the page the link goes to
         */
        "href": string | undefined;
        /**
          * Set component states
         */
        "interactionState": 'default' | 'hover' | 'active' | 'focus' | 'disabled';
        /**
          * The name attribute specifies the name for a <button> element.
         */
        "name": string | undefined;
        /**
          * The rel attribute specifies the relationship between the current document and the linked document
         */
        "rel": string | undefined;
        /**
          * The target attribute specifies where to open the linked document
         */
        "target": string | undefined;
    }
}
declare global {
    interface HTMLGcdsButtonElement extends Components.GcdsButton, HTMLStencilElement {
    }
    var HTMLGcdsButtonElement: {
        prototype: HTMLGcdsButtonElement;
        new (): HTMLGcdsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-button": HTMLGcdsButtonElement;
    }
}
declare namespace LocalJSX {
    interface GcdsButton {
        /**
          * Set the main style
         */
        "buttonRole"?: 'primary' | 'secondary' | 'danger' | 'skip-to-content';
        /**
          * Set the style variant
         */
        "buttonStyle"?: 'solid' | 'outline' | 'text-only';
        /**
          * Set button types
         */
        "buttonType"?: 'submit' | 'reset' | 'button' | 'link';
        /**
          * StyleAPI: custom background color.
         */
        "customBackgroundColor"?: string | undefined;
        /**
          * StyleAPI: custom border color.
         */
        "customBorderColor"?: string | undefined;
        /**
          * StyleAPI: custom border style.
         */
        "customBorderStyle"?: string | undefined;
        /**
          * StyleAPI: custom border weight.
         */
        "customBorderWeight"?: string | undefined;
        /**
          * StyleAPI: custom box shadow.
         */
        "customBoxShadow"?: string | undefined;
        /**
          * StyleAPI: custom btext transform.
         */
        "customCapitalization"?: string | undefined;
        /**
          * StyleAPI: custom display.
         */
        "customDisplay"?: string | undefined;
        /**
          * StyleAPI: custom margin.
         */
        "customMargin"?: string | undefined;
        /**
          * The download attribute specifies that the target (the file specified in the href attribute) will be downloaded when a user clicks on the hyperlink
         */
        "download"?: string | undefined;
        /**
          * The href attribute specifies the URL of the page the link goes to
         */
        "href"?: string | undefined;
        /**
          * Set component states
         */
        "interactionState"?: 'default' | 'hover' | 'active' | 'focus' | 'disabled';
        /**
          * The name attribute specifies the name for a <button> element.
         */
        "name"?: string | undefined;
        /**
          * Emitted when the button loses focus.
         */
        "onGcdsBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the button has focus.
         */
        "onGcdsFocus"?: (event: CustomEvent<void>) => void;
        /**
          * The rel attribute specifies the relationship between the current document and the linked document
         */
        "rel"?: string | undefined;
        /**
          * The target attribute specifies where to open the linked document
         */
        "target"?: string | undefined;
    }
    interface IntrinsicElements {
        "gcds-button": GcdsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcds-button": LocalJSX.GcdsButton & JSXBase.HTMLAttributes<HTMLGcdsButtonElement>;
        }
    }
}
