name: Release Generator
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: sre_app_token
        with:
          app-id: ${{ secrets.SRE_APP_ID }}
          private-key: ${{ secrets.SRE_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
